[package]
name = "easyocr-rs"
version = "0.1.0"
edition = "2024"

# [lib]
# crate-type = ["dylib", "rlib"]

[dependencies]
pyo3 = { version = "0.25", features = ["auto-initialize"] }
error-pile = { git = "https://github.com/Ram-Hotel-Management/error-pile.git" }
image = "0.25.6"

