[package]
name = "easyocr-rs"
version = "0.1.0"
edition = "2024"

# [lib]
# crate-type = ["dylib", "rlib"]

[dependencies]
pyo3 = { version = "0.24.2", features = ["auto-initialize"] }
thiserror = "2.0.12"

